/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetOutcomes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMode"];
        put: operations["SetMode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetExperimentRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMetricsSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnomalySignal: {
            /** Format: uuid */
            signalId: string;
            /** Format: date-time */
            detectedAtUtc: string;
            target: components["schemas"]["ServiceTarget"];
            metricName: string;
            detector: components["schemas"]["DetectorType"];
            severity: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number | string;
            /** Format: double */
            pValue: number | string;
            /** Format: double */
            observedValue: number | string;
            /** Format: double */
            expectedValue: number | string;
            window: components["schemas"]["TimeWindow"];
            /** Format: uuid */
            experimentRunId?: null | string;
        };
        /** @enum {unknown} */
        DecidedBy: "Llm" | "RuleEngine" | "Fallback";
        /** @enum {unknown} */
        DetectorType: "SpikeDetection" | "ChangePointDetection" | "Forecast";
        ExperimentRunSummary: {
            /** Format: uuid */
            experimentRunId: string;
            scenario: string;
            arm: string;
            /** Format: int32 */
            repetition: number | string;
            /** Format: int32 */
            runOrder: number | string;
            /** Format: int32 */
            randomizationSeed: number | string;
            /** Format: double */
            targetRps: number | string;
            /** Format: double */
            achievedRps?: null | number | string;
            /** Format: int32 */
            chaosSeed: number | string;
            /** Format: int32 */
            loadSeed: number | string;
            /** Format: double */
            injectionPhase: number | string;
            mode: string;
            forecastEnabled: boolean;
            /** Format: int32 */
            forecastHorizonMinutes?: null | number | string;
            llmModelDigest?: null | string;
            /** Format: int32 */
            llmTimeoutSeconds?: null | number | string;
            /** Format: int32 */
            llmNumCtx?: null | number | string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            onsetAtUtc?: null | string;
            /** Format: date-time */
            windowEndAtUtc?: null | string;
            /** Format: date-time */
            recoveredAtUtc?: null | string;
            terminationState?: null | string;
            /** Format: double */
            cpuTempMaxCelsius?: null | number | string;
            /** Format: double */
            cpuClockAvgMhz?: null | number | string;
            /** Format: int32 */
            wslMemoryGb: number | string;
            /** Format: int32 */
            wslProcessors: number | string;
            gitCommitSha: string;
        };
        HealingAction: {
            /** Format: uuid */
            actionId: string;
            type: components["schemas"]["HealingActionType"];
            target: components["schemas"]["ServiceTarget"];
            parameters?: {
                [key: string]: string;
            };
            /** Format: int32 */
            order: number | string;
            dryRun?: boolean;
        };
        /** @enum {unknown} */
        HealingActionType: "ScaleUp" | "RestartPod" | "ToggleFeatureFlag" | "NoOp";
        HealingOutcome: {
            /** Format: uuid */
            outcomeId: string;
            /** Format: uuid */
            planId: string;
            /** Format: date-time */
            appliedAtUtc: string;
            /** Format: date-time */
            verifiedAtUtc: string;
            status: components["schemas"]["HealingOutcomeStatus"];
            sloRestored: boolean;
            /** Format: double */
            timeToRecoverySeconds: number | string;
            metricsBefore: components["schemas"]["RecentMetrics"];
            metricsAfter: components["schemas"]["RecentMetrics"];
            errorMessage?: null | string;
        };
        /** @enum {unknown} */
        HealingOutcomeStatus: "Succeeded" | "Failed" | "PartiallyApplied" | "Rejected" | "TimedOut";
        HealingPlan: {
            /** Format: uuid */
            planId: string;
            /** Format: uuid */
            contextId: string;
            /** Format: date-time */
            createdAtUtc: string;
            decidedBy: components["schemas"]["DecidedBy"];
            rationale: string;
            /** Format: double */
            confidence: number | string;
            actions?: components["schemas"]["HealingAction"][];
            expectedOutcome: string;
            /** Format: int32 */
            verificationWindowSeconds?: number | string;
            llmTrace: components["schemas"]["LlmTrace"];
        };
        LlmTrace: {
            promptHash?: null | string;
            model?: null | string;
            /** Format: int64 */
            latencyMs?: number | string;
            /** Format: int32 */
            attempts?: number | string;
            failureReasons?: string[];
        };
        MetricSample: {
            metricName: string;
            target: components["schemas"]["ServiceTarget"];
            /** Format: date-time */
            timestampUtc: string;
            /** Format: double */
            value: number | string;
            labels?: {
                [key: string]: string;
            };
        };
        ModeResponse: {
            mode: components["schemas"]["PlatformMode"];
        };
        /** @enum {unknown} */
        PlatformMode: "Observe" | "DryRun" | "Active";
        RecentMetrics: {
            /** Format: double */
            cpuUtilizationPct: number | string;
            /** Format: int64 */
            memoryWorkingSetBytes: number | string;
            /** Format: double */
            requestRatePerSecond: number | string;
            /** Format: double */
            errorRatePct: number | string;
            /** Format: double */
            latencyP99Ms: number | string;
            /** Format: int32 */
            queueDepth: number | string;
            errorsByType?: {
                [key: string]: number | string;
            };
        };
        ResourceSpec: {
            cpu: string;
            memory: string;
        };
        ServiceTarget: {
            service: string;
            namespace: string;
            pod?: null | string;
            podUid?: null | string;
        };
        SetModeRequest: {
            mode: components["schemas"]["PlatformMode"];
        };
        /** @enum {unknown} */
        Severity: "Low" | "Medium" | "High" | "Critical";
        TimeWindow: {
            /** Format: date-time */
            fromUtc: string;
            /** Format: date-time */
            toUtc: string;
        };
        TopologyInfo: {
            service: string;
            /** Format: int32 */
            currentReplicas: number | string;
            /** Format: int32 */
            desiredReplicas: number | string;
            resourceRequests: components["schemas"]["ResourceSpec"];
            resourceLimits: components["schemas"]["ResourceSpec"];
            dependsOn?: string[];
            dependedOnBy?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetTopology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyInfo"][];
                };
            };
        };
    };
    GetSignals: {
        parameters: {
            query: {
                Limit: number | string;
                ExperimentRunId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalySignal"][];
                };
            };
        };
    };
    GetPlans: {
        parameters: {
            query: {
                Limit: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealingPlan"][];
                };
            };
        };
    };
    GetOutcomes: {
        parameters: {
            query: {
                Limit: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealingOutcome"][];
                };
            };
        };
    };
    GetMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeResponse"];
                };
            };
        };
    };
    SetMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetModeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeResponse"];
                };
            };
        };
    };
    GetExperimentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRunSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMetricsSeries: {
        parameters: {
            query: {
                MetricName: string;
                Service: string;
                FromUtc: string;
                ToUtc: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSample"][];
                };
            };
        };
    };
}
