<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>norn-shop-payment-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Norn.Shop.Contracts\Norn.Shop.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Norn.BuildingBlocks.Telemetry\Norn.BuildingBlocks.Telemetry.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Norn.BuildingBlocks.Web\Norn.BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Norn.BuildingBlocks.Messaging\Norn.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
