// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norn.Knowledge;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norn.Knowledge.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    partial class KnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Norn.Knowledge.Entities.AnomalyContextRow", b =>
                {
                    b.Property<Guid>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("context_hash");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("ExperimentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_run_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PrimarySignalId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_signal_id");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.HasKey("ContextId");

                    b.HasIndex("ExperimentRunId");

                    b.HasIndex("PrimarySignalId");

                    b.HasIndex("Service", "CreatedAtUtc");

                    b.ToTable("anomaly_contexts", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.AnomalySignalRow", b =>
                {
                    b.Property<Guid>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("signal_id");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<Guid?>("ExperimentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_run_id");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("metric_name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.HasKey("SignalId");

                    b.HasIndex("ExperimentRunId");

                    b.HasIndex("Service", "MetricName", "DetectedAtUtc");

                    b.ToTable("anomaly_signals", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.ExperimentRunRow", b =>
                {
                    b.Property<Guid>("ExperimentRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_run_id");

                    b.Property<double?>("AchievedRps")
                        .HasColumnType("double precision")
                        .HasColumnName("achieved_rps");

                    b.Property<string>("Arm")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("arm");

                    b.Property<int>("ChaosSeed")
                        .HasColumnType("integer")
                        .HasColumnName("chaos_seed");

                    b.Property<double?>("CpuClockAvgMhz")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_clock_avg_mhz");

                    b.Property<double?>("CpuTempMaxCelsius")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_temp_max_celsius");

                    b.Property<bool>("ForecastEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("forecast_enabled");

                    b.Property<int?>("ForecastHorizonMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("forecast_horizon_minutes");

                    b.Property<string>("GitCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("git_commit_sha");

                    b.Property<double>("InjectionPhase")
                        .HasColumnType("double precision")
                        .HasColumnName("injection_phase");

                    b.Property<string>("LlmModelDigest")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("llm_model_digest");

                    b.Property<int?>("LlmNumCtx")
                        .HasColumnType("integer")
                        .HasColumnName("llm_num_ctx");

                    b.Property<int?>("LlmTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("llm_timeout_seconds");

                    b.Property<int>("LoadSeed")
                        .HasColumnType("integer")
                        .HasColumnName("load_seed");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset?>("OnsetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onset_at_utc");

                    b.Property<int>("RandomizationSeed")
                        .HasColumnType("integer")
                        .HasColumnName("randomization_seed");

                    b.Property<DateTimeOffset?>("RecoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at_utc");

                    b.Property<int>("Repetition")
                        .HasColumnType("integer")
                        .HasColumnName("repetition");

                    b.Property<int>("RunOrder")
                        .HasColumnType("integer")
                        .HasColumnName("run_order");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("scenario");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<double>("TargetRps")
                        .HasColumnType("double precision")
                        .HasColumnName("target_rps");

                    b.Property<string>("TerminationState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("termination_state");

                    b.Property<DateTimeOffset?>("WindowEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_at_utc");

                    b.Property<int>("WslMemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("wsl_memory_gb");

                    b.Property<int>("WslProcessors")
                        .HasColumnType("integer")
                        .HasColumnName("wsl_processors");

                    b.HasKey("ExperimentRunId");

                    b.HasIndex("Scenario", "Arm", "Repetition");

                    b.ToTable("experiment_runs", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.HealingOutcomeRow", b =>
                {
                    b.Property<Guid>("OutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outcome_id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("OutcomeId");

                    b.HasIndex("PlanId");

                    b.ToTable("healing_outcomes", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.HealingPlanRow", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("PlanId");

                    b.HasIndex("ContextId");

                    b.ToTable("healing_plans", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.LlmTraceRow", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("trace_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("PromptHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_hash");

                    b.HasKey("TraceId");

                    b.HasIndex("PlanId");

                    b.ToTable("llm_traces", "platform");
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.AnomalyContextRow", b =>
                {
                    b.HasOne("Norn.Knowledge.Entities.AnomalySignalRow", null)
                        .WithMany()
                        .HasForeignKey("PrimarySignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.HealingOutcomeRow", b =>
                {
                    b.HasOne("Norn.Knowledge.Entities.HealingPlanRow", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.HealingPlanRow", b =>
                {
                    b.HasOne("Norn.Knowledge.Entities.AnomalyContextRow", null)
                        .WithMany()
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Norn.Knowledge.Entities.LlmTraceRow", b =>
                {
                    b.HasOne("Norn.Knowledge.Entities.HealingPlanRow", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
